"""add phone field to Blog model

Revision ID: 8ddc1005c507
Revises: 531aec8eb5d2
Create Date: 2025-04-18 14:30:31.850267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8ddc1005c507'
down_revision: Union[str, None] = '531aec8eb5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Blogs_id', table_name='blogs')
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=False)
    op.add_column('users', sa.Column('phone', sa.Integer(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index('ix_Users_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_Users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.create_index('ix_Blogs_id', 'blogs', ['id'], unique=False)
    # ### end Alembic commands ###
